name: Build and push Docker image



on:
  workflow_dispatch:
    inputs:
      spark_version:
        description: 'Spark version to use'
        required: true
        type: string
        default: '3.5.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: little-core-labs/get-git-tag@v3.0.1
      id: tagName

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Load .env file
      id: dotenv
      uses: falti/dotenv-action@v1.1.2
      with:
        path: versions/${{ inputs.spark_version }}/.env
        log-variables: true
        export-variables: true

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: portablespark/little-spark:${{ github.ref_name }}
        build-args: |
          PYTHON_VERSION=${{ steps.dotenv.outputs.python_version }}
          SPARK_VERSION=${{ steps.dotenv.outputs.spark_version }}
          SCALA_VERSION=${{ steps.dotenv.outputs.scala_version }}
          HADOOP_VERSION=${{ steps.dotenv.outputs.hadoop_version }}
          JAVA_VERSION=${{ steps.dotenv.outputs.java_version }}
